cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name

credentials:
  usernames:
    "jchavesm2017@gmail.com":        # ðŸ‘ˆ EL USERNAME ES EL EMAIL
      email: "jchavesm2017@gmail.com"
      first_name: "Jose"
      last_name: "Chaves"
      password: "1234"       # en string
      roles:
        - admin

    "capitalrentalscr@gmail.com":
      email: "capitalrentalscr@gmail.com"
      first_name: "Julian"
      last_name: "Sanchez"
      password: "itoxgay"
      roles:
        - viewer
