cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name

credentials:
  usernames:
    "jose@gmail.com":        # ðŸ‘ˆ EL USERNAME ES EL EMAIL
      email: "jose@gmail.com"
      first_name: "Jose"
      last_name: "Chaves"
      password: "1234"       # en string
      roles:
        - admin

    "admin2@gmail.com":
      email: "admin2@gmail.com"
      first_name: "Admin"
      last_name: "User"
      password: "abcd"
      roles:
        - viewer
