cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name

credentials:
  usernames:
    jose:
      email: jose@gmail.com
      first_name: Jose
      last_name: Chaves
      password: 1234    # en texto plano para empezar
      roles:
        - admin
